<?php

use App\Http\Controllers\api\BookingController;
use App\Http\Controllers\api\ClientController;
use App\Http\Controllers\api\ClubSettingController;
use App\Http\Controllers\api\CustomerPurchasesController;
use App\Http\Controllers\api\DashboardController;
use App\Http\Controllers\api\ExportController;
use App\Http\Controllers\api\FinanceController;
use App\Http\Controllers\api\HistoryDepositsController;
use App\Http\Controllers\api\HistorySalesController;
use App\Http\Controllers\api\LicensesController;
use App\Http\Controllers\api\LoggerController;
use App\Http\Controllers\api\MapController;
use App\Http\Controllers\api\PayTerminalController;
use App\Http\Controllers\api\PositionController;
use App\Http\Controllers\api\PromoController;
use App\Http\Controllers\api\ReceiptController;
use App\Http\Controllers\api\RegistrationController;
use App\Http\Controllers\api\ReturnInfoController;
use App\Http\Controllers\api\SendToAdminController;
use App\Http\Controllers\api\ShopController;
use App\Http\Controllers\api\SoundController;
use App\Http\Controllers\api\TariffController;
use App\Http\Controllers\api\TariffStatisticController;
use App\Http\Controllers\api\TaskController;
use App\Http\Controllers\api\TestController;
use App\Http\Controllers\api\UserAccessController;
use App\Http\Controllers\api\UserController;
use App\Http\Controllers\api\UserGroupController;
use App\Http\Controllers\api\UserInfoController;
use App\Http\Controllers\api\ZoneController;
use App\Http\Controllers\WebHooks\ShiftController;
use Illuminate\Support\Facades\Route;

Route::post('testget', [\App\Http\Controllers\TestController::class, 'get'])->name('testGet');
Route::post('saveMapPosition', [MapController::class, 'saveMapPosition'])->name('saveMapPosition');
Route::post('getMapPosition', [MapController::class, 'getMapPosition'])->name('getMapPosition');
Route::post('saveNewPosition', [MapController::class, 'saveNewPosition'])->name('saveNewPosition');
Route::post('findusers', [App\Http\Controllers\api\UserController::class, 'UsersFind'])->name('UsersFind');
Route::post('age-filter', [App\Http\Controllers\api\UserController::class, 'ageFilter']);
Route::post('user/send-new-mind', [App\Http\Controllers\api\UserController::class, 'sendNewMind']);
Route::post('user/get-notes', [App\Http\Controllers\api\UserController::class, 'getNotes']);
Route::post('getSmena', [App\Http\Controllers\api\FinanceController::class, 'getSmena'])->name('getSmena');
Route::post('findopenshift', [App\Http\Controllers\api\FinanceController::class, 'findOpenShift'])->name('findOpenShift');
Route::post('getGames', [App\Http\Controllers\api\GameController::class, 'getGames'])->name('getGames');
Route::post('changeStatus', [App\Http\Controllers\api\GameController::class, 'changeStatus'])->name('changeStatus');
Route::post('searchGame', [App\Http\Controllers\api\GameController::class, 'searchGame'])->name('searchGame');
Route::post('finance/all', [FinanceController::class, 'getAllFinance']);
Route::post('finance/filter', [FinanceController::class, 'filterFinance']);
Route::post('finance/admins', [FinanceController::class, 'getAdmins']);
Route::post('finance/clients', [FinanceController::class, 'getClients']);
Route::post('shift/close', [ShiftController::class, 'close'])->name('shift.close');
Route::post('shift/open', [ShiftController::class, 'open'])->name('shift.open');
Route::post('verifyopenshift', [FinanceController::class, 'verifyOpenShift'])->name('verifyOpenShift');
Route::post('verifycloseshift', [FinanceController::class, 'verifyCloseShift'])->name('verifyCloseShift');
Route::post('games/getGameById', [App\Http\Controllers\api\GameController::class, 'getGameById'])->name('getGameById');
Route::post('games/savegame', [App\Http\Controllers\api\GameController::class, 'saveGame'])->name('saveGame');
Route::post('openOpenModal', [ShiftController::class, 'openOpenModal'])->name('openOpenModal');
Route::post('openCloseModal', [ShiftController::class, 'openCloseModal'])->name('openCloseModal');
Route::post('zone/getZone', [ZoneController::class, 'getZone'])->name('getZone');
Route::post('map/findpc', [MapController::class, 'findPCForAdd'])->name('findPCForAdd');
Route::post('sendMassage', [FinanceController::class, 'sendMassage'])->name('sendMassage');
Route::post('closepay', [FinanceController::class, 'closePaymentWindow'])->name('closePaymentWindow');
Route::post('shop/get', [ShopController::class, 'getAll']);
Route::post('shop/find', [ShopController::class, 'find']);
Route::post('client/all', [ClientController::class, 'getClients']);
Route::post('shop/find/client', [ShopController::class, 'searchClient']);
Route::post('booking/all', [BookingController::class, 'getAllClients']);
Route::post('booking/cancel', [BookingController::class, 'cancelBooking']);
Route::post('booking/get-all', [BookingController::class, 'getAllBookingsPerDay']);
Route::post('booking/get-all-api', [BookingController::class, 'getAllBookingsPerDayAPI']);
Route::post('booking/get-hours', [BookingController::class, 'getAllBookingsHours']);
Route::post('zone/add', [ZoneController::class, 'addZone']);
Route::post('promo/save', [PromoController::class, 'save']);
Route::post('promo/get', [PromoController::class, 'get']);
Route::post('tasks/tasks', [TaskController::class, 'tasks']);
Route::post('tasks/get', [TaskController::class, 'getTasks']);
Route::post('tasks/users', [TaskController::class, 'users']);
Route::post('tasks/save', [TaskController::class, 'saveAddModal']);
Route::post('tasks/save/edit', [TaskController::class, 'saveEditModal']);
Route::post('tasks/new-status', [TaskController::class, 'getNewStatus']);
Route::post('tasks/save-new-status', [TaskController::class, 'saveNewStatus']);
Route::post('tasks/all', [TaskController::class, 'allTasks']);
Route::post('booking/draw', [BookingController::class, 'draw']);
Route::post('store/addedit', [ShopController::class, 'addEdit']);
Route::post('price/get', [TariffController::class, 'getTariff']);
Route::post('user/getpermissions', [UserController::class, 'getPermisions']);
Route::post('position/getuser', [PositionController::class, 'getUsers']);
Route::post('position/get', [PositionController::class, 'getPositions']);
Route::post('licenses', [LicensesController::class, 'licenses']);
Route::post('category/save', [LicensesController::class, 'categorySave']);
Route::post('tariff/save', [TariffController::class, 'save']);
Route::post('tariff/zone', [TariffController::class, 'zone']);
Route::post('map/user-id', [MapController::class, 'mapUserId']);
Route::post('reservations', [BookingController::class, 'reservations']);
Route::post('user/cash', [BookingController::class, 'userCash']);
Route::post('finance/data', [FinanceController::class, 'financeModalData']);
Route::post('userinfo/shifts', [UserInfoController::class, 'shifts']);
Route::post('games/addsteam', [App\Http\Controllers\api\GameController::class, 'addSteamAccount']);
Route::post('promo/codes', [PromoController::class, 'codes']);
Route::post('club/setting/disign', [ClubSettingController::class, 'disignData']);
Route::post('diagram/calc', [FinanceController::class, 'diagramCalc']);
Route::post('user_group', [UserGroupController::class, 'getGroup']);
Route::post('user_group/add', [UserGroupController::class, 'addUserGroup']);
Route::post('user_group/edit', [UserGroupController::class, 'editGroupSave']);
Route::post('user_group/delete', [UserGroupController::class, 'delete']);
Route::post('message', [SendToAdminController::class, 'getMessage']);
Route::post('deposit', [HistoryDepositsController::class, 'getDeposits']);
Route::post('map/stopsos', [MapController::class, 'stopSOS']);
Route::post('sales', [HistorySalesController::class, 'getsales']);
Route::post('sale', [HistorySalesController::class, 'sale']);
Route::post('statistic', [DashboardController::class, 'statistic']);
Route::post('store-out/save', [ShopController::class, 'storeOutSave']);
Route::post('client/getlogin', [ClientController::class, 'getLogin']);
Route::post('booking/statistic', [TariffStatisticController::class, 'statistic']);
Route::post('user/accesses', [UserAccessController::class, 'accesses']);
Route::post('user/access/update', [UserAccessController::class, 'update']);
Route::post('user/send_invitation', [PositionController::class, 'SendInvitation']);
Route::post('user/registration', [RegistrationController::class, 'registration']);
Route::post('user/verify', [RegistrationController::class, 'verifyEmail']);
Route::post('client/add_amount', [ClientController::class, 'addAmount']);
Route::post('cashbox_type', [PayTerminalController::class, 'cashboxType']);
Route::post('cashbox_connect_type', [PayTerminalController::class, 'cashboxConnectType']);
Route::post('cashbox/save', [PayTerminalController::class, 'save']);
Route::post('cashbox/setting', [PayTerminalController::class, 'setting']);
Route::post('sound/upload', [SoundController::class, 'upload']);
Route::post('warehouse/add', [ShopController::class, 'addToWarehouse']);
Route::post('warehouse/allreceipts', [ReceiptController::class, 'allReceipts']);
Route::post('warehouse/filter', [ReceiptController::class, 'filter']);
Route::post('promo/details', [PromoController::class, 'details']);
Route::post('store/operation/type', [ShopController::class, 'getStoreOparationType']);
Route::post('clients/purchases', [CustomerPurchasesController::class, 'getPurchases']);
Route::post('clients/delivery', [CustomerPurchasesController::class, 'delivery']);
Route::post('purchases/filter', [CustomerPurchasesController::class, 'filter']);
Route::post('purchases/details', [CustomerPurchasesController::class, 'details']);
Route::post('return/info', [ReturnInfoController::class, 'info']);
Route::post('return/filter', [ReturnInfoController::class, 'filter']);
Route::post('export', [ExportController::class, 'export'])->name('export');
Route::post('export/clients', [ExportController::class, 'exportClients'])->name('exportClients');
Route::post('import/clients', [ExportController::class, 'importClients'])->name('importClients');
Route::post('task/get-new', [TaskController::class, 'getNewTask']);
Route::post('task/unvisible', [TaskController::class, 'unvisibleToast']);
Route::post('log/create', [LoggerController::class, 'createLog']);


Route::post('test/all', [TestController::class, 'all']);
Route::post('test/perday', [TestController::class, 'perday']);
Route::post('test', [TestController::class, 'test']);
